* About the project

I was fed up with some of the peculiarities of the R programming language at the same time that I started dipping my toes into the world of Scheme. The elegance of this language struck me. To be able for me to use it productively it would need to support scientific computing. So I started implementing libraries for bioinformatics, as I am most familiar with this field. I write this in the hope that it will get adopted and grow in popularity to the size of support scientific computing has in R or python. Surely this is a harebrained scheme!
Documentation can be found online at [[http://harebrained.sam-d.com][harebrained.sam-d.com]]
** Status
Currently the library is still in flux until the 1.0 release. See [[* Roamap]] for planned features.

* Getting started
** Installation
(harebrained scheme) is currently distributed as a guix package inside its source code repository. See [[* Usage]] on how to use/install.

* Usage
First we will start a guix shell with the required packages to work in a chez-scheme environment:

#+begin_src bash
% guix shell -f guix.scm chez-scheme chez-srfi

% scheme
#+end_src

Inside chez-scheme we can then load the complete (harebrained scheme) package and start working:

#+begin_src scheme 
> (import (harebrained scheme))

> (bioseq->string (dna-reverse-complement (make-bioseq "ACTG")))

"CAGT"
#+end_src

Documentation can be found online at [[http://harebrained.sam-d.com][harebrained.sam-d.com]]
* Roadmap
+ [ ]  add biological features (i.e. intervals on genomes) from BED files and such
+ [ ] add API for pairwise alignments
+ [ ] add API for small reads (e.g. from FASTQ files)
+ [ ] add library for plotting à la ggplot
+ [ ] add a data frame type

* Contributing
Contributions are what make the open source community such an amazing place to learn, inspire, and create. Any contributions you make are *greatly appreciated*.

If you have a suggestion that would make this better, please fork the repo and create a pull request. You can also simply open an issue with the tag "enhancement".
Don't forget to give the project a star! Thanks again!

1. Fork the Project
2. Create your Feature Branch (`git checkout -b feature/AmazingFeature`)
3. Commit your Changes (`git commit -m 'Add some AmazingFeature'`)
4. Push to the Branch (`git push origin feature/AmazingFeature`)
5. Open a Pull Request

* License
Distributed under the Gnu General Public License v3. See ~LICENSE~ for more details.
