#!r6rs
(import (rnrs base)
	(srfi :64)
	(harebrained tests runner)
	(harebrained bio collections))
(test-runner-current (scheme-test-runner #f #f))

(test-begin "collections-tests")
(test-group "biocol record interface"
	    (test-equal "bla" (biocol-name (make-biocol "bla" '()))))
(test-group "biocol map interface"
	    (test-assert (biocol-contains? (make-biocol "test" '(1) '("bla")) "bla"))
	    (test-assert (not (biocol-contains? (make-biocol "test" '(1) '("bla")) "blupp")))
	    (let ((v (vector 1 2 3))
		  (v2 (vector 'a 'b 'c)))
	      (test-equal v (biocol-ref (make-biocol "" (list v) '("key")) "key"))
	      (test-equal v2 (biocol-ref (biocol-set (make-biocol "" (list v) '("bla")) "bla" v2) "bla")))
	    (let* ((bc1 (make-biocol "bc1" '(a) '("bla")))
		   (bc2 (make-biocol "bc2" '(b) '("blupp")))
		   (bc (biocol-append bc1 bc2)))
	      (test-assert (biocol-contains? bc "bla"))
	      (test-assert (biocol-contains? bc "blupp"))
	      (test-assert (not (biocol-contains? bc "")))
	      (test-eq 'a (biocol-ref bc "bla"))
	      (test-eq 'b (biocol-ref bc "blupp")))
	    (let ((bc (biocol-set (biocol-set (make-biocol "test") "b" 'b) "a" 'a)))
	      (test-assert (biocol-contains? (biocol-set bc "c" 'c) "c"))
	      (test-equal "test" (biocol-name bc))
	      (test-eq 'a (biocol-ref bc "a"))
	      (test-eq 'b (biocol-ref bc "b"))
	      (test-eq 'c (biocol-ref (biocol-set bc "b" 'c) "b")))
	    (test-eq 'b (biocol-ref (biocol-set (biocol-set (make-biocol) "a" 'a) "a" 'b) "a" ))
	    (let ((bc (biocol-append (biocol-set (make-biocol "name1") "a" 'a) (biocol-set (make-biocol "name2") "b" 'b))))
	      (test-equal "name1" (biocol-name bc))
	      (test-equal (biocol-length bc) (biocol-length (biocol-append bc (make-biocol "name2"))))
	      (test-equal (biocol-length bc) (biocol-length (biocol-append (make-biocol "name2") bc)))
	      (test-equal "name2" (biocol-name (biocol-append (make-biocol "name2") bc)))))
 
(test-group "biocol sequence interface"
	    (let* ((bc1 (make-biocol "bc1" '(a) '("bla")))
		   (bc2 (make-biocol "bc2" '(b) '("blupp")))
		   (bc (biocol-append bc1 bc2)))
	      (test-eq 2 (biocol-length bc))
	      (test-eq 'a (biocol-ref bc 0))
	      (test-eq 'b (biocol-ref bc 1)))
	    (let ((bc (biocol-set (biocol-set (make-biocol "test") "b" 'b) "a" 'a)))
	      (test-equal "test" (biocol-name bc))
	      (test-eq 2 (biocol-length bc))
	      (test-eq 'a (biocol-ref bc 1))
	      (test-eq 'b (biocol-ref bc 0))
	      (test-eq 'c (biocol-ref (biocol-set bc "b" 'c) 0)))
	    (let ((bc (biocol-set (make-biocol "bla") "a" 'a)))
	      (test-eq 1 (biocol-length bc))))
(test-end "collections-tests")
